# Generated by Django 3.1.6 on 2021-02-16 11:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('sqft', models.IntegerField()),
                ('garage', models.IntegerField(default=0)),
                ('lot_size', models.DecimalField(decimal_places=1, max_digits=5)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('main_image', models.ImageField(upload_to='photos/%Y/%m%d/')),
                ('image1', models.ImageField(blank=True, upload_to='photos/%Y/%m%d/')),
                ('image2', models.ImageField(blank=True, upload_to='photos/%Y/%m%d/')),
                ('image3', models.ImageField(blank=True, upload_to='photos/%Y/%m%d/')),
                ('image4', models.ImageField(blank=True, upload_to='photos/%Y/%m%d/')),
                ('image5', models.ImageField(blank=True, upload_to='photos/%Y/%m%d/')),
                ('image6', models.ImageField(blank=True, upload_to='photos/%Y/%m%d/')),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtor')),
            ],
        ),
    ]
